"""empty message

Revision ID: 54d4b297da41
Revises: 
Create Date: 2024-07-15 17:03:33.762106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d4b297da41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_levels'))
    )
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_players'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('input', sa.String(), nullable=False),
    sa.Column('time', sa.String(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.id'], name=op.f('fk_games_level_id_levels')),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name=op.f('fk_games_player_id_players')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    op.drop_table('players')
    op.drop_table('levels')
    # ### end Alembic commands ###
